import Head from 'next/head'
import Image from 'next/image'
import { Swiper, SwiperSlide } from 'swiper/react'
import { Pagination } from 'swiper'

import 'swiper/css'
import 'swiper/css/pagination'

import Header from '../components/header'
import Footer from '../components/footer'
import Button from '../components/button'
import IllustrationImage from '../public/illustration-intro.svg?url'

import avatarAnisha from '../public/avatar-anisha.png?url'
import avatarAli from '../public/avatar-ali.png?url'
import avatarRichard from '../public/avatar-richard.png?url'
import avatarShanai from '../public/avatar-shanai.png?url'

export default function Home() {
    return (
        <>
            <Head>
                <title>Manage</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main>
                <SectionAboveFold />
                <SectionFunctions />
                <SectionTestimonials />
                <SectionSimplify />
            </main>
            <Footer />
        </>
    )
}

const SectionAboveFold = () => {
    return (
        <section className="mx-auto w-10/12 max-w-screen-xl pt-16 pb-28">
            <div className=" absolute top-0 right-0 -z-10 h-1/2 w-full max-w-xl overflow-hidden md:h-3/4 md:w-1/2">
                <div className="h-full w-full translate-x-[40%] -translate-y-[40%] scale-[1.7] transform bg-[url('/bg-tablet-pattern.svg')] bg-contain bg-no-repeat "></div>
            </div>
            <div className="flex flex-col-reverse gap-x-16  md:flex-row  ">
                <div className=" flex flex-col justify-center gap-5 text-center md:grow-[1] md:basis-2/5 md:text-left lg:basis-1/2">
                    <h1 className="lg:text-6xl">
                        Bring everyone together to build better products.
                    </h1>
                    <p className="mb-4">
                        Manage makes it simple for software teams to plan
                        day-to-day tasks while keeping the larger team goals in
                        view.
                    </p>
                    <div>
                        <Button variant="primary" internalHref="/">
                            Get Started
                        </Button>
                    </div>
                </div>

                <div className="md:grow-[2] md:basis-3/5 lg:basis-1/2">
                    <Image
                        src={IllustrationImage}
                        alt="Graphs Illustrations"
                        className="w-full"
                        width={100}
                        height={100}
                    />
                </div>
            </div>
        </section>
    )
}

const SectionFunctions = () => {
    const content = [
        {
            title: 'Track company-wide progress',
            desc: `Track company-wide progress See how your day-to-day tasks fit into the wider vision. 
            Go from tracking progress at the milestone level all the way done to the smallest of details. 
            Never lose sight of the biggerpicture again.`,
        },
        {
            title: 'Advanced built-in reports',
            desc: `Set internal delivery estimates and track progress toward company goals. 
            Our customisable dashboard helps you build out the reports you need to keep keystakeholders informed.`,
        },
        {
            title: 'Everything you need in one place',
            desc: `Stop jumping from one service to another to communicate, store files, 
            track tasks and share documents. Manage offers an all-in-one team 
            productivity solution.`,
        },
    ]
    return (
        <section className="relative">
            {/* <div className="absolute top-0 right-0 -z-10 h-[400px] w-full -translate-y-[100%] overflow-hidden md:hidden lg:left-0 lg:right-auto lg:block">
                <div className="h-full w-full translate-x-[60%] transform bg-[url('/bg-tablet-pattern.svg')] bg-contain bg-no-repeat "></div>
            </div> */}

            <div className="mx-auto max-w-screen-xl pb-28 text-center leading-relaxed lg:flex lg:w-10/12 lg:gap-8 lg:text-left lg:text-left">
                <div className="mx-auto w-11/12 pb-8 ">
                    <h2 className="mb-8">What’s different about Manage?</h2>
                    <p className="mx-auto w-3/4 lg:mx-0">
                        Manage provides all the functionality your team needs,
                        without the complexity. Our software is tailor-made for
                        modern digital product teams.
                    </p>
                </div>
                <ul className="flex flex-col gap-8 pl-4 text-left md:gap-16 md:pl-16">
                    {content.map((item, index) => {
                        return (
                            <li key={index} className="">
                                <h3 className="text-md mb-4 flex justify-center rounded-l-full bg-red-light lg:bg-transparent">
                                    <span className="text-full  inline-block rounded-full bg-red-full px-7 py-2 text-white">
                                        {'0' + (index + 1)}
                                    </span>
                                    <span className="ml-4 grow self-center">
                                        {item.title}
                                    </span>
                                </h3>
                                <p className="text-left md:ml-24">
                                    {item.desc}
                                </p>
                            </li>
                        )
                    })}
                </ul>
            </div>
        </section>
    )
}

const SectionTestimonials = () => {
    const testimonials = [
        {
            name: 'Anisha Li',
            content: `Manage has supercharged our team’s workflow. The ability to maintain 
        visibility on larger milestones at all times keeps everyone motivated.`,
            avatar: avatarAnisha,
        },
        {
            name: 'Richad Watts',
            content: `Manage allows us to provide structure and process. It keeps us organized
            and focused. I can’t stop recommending them to everyone I talk to!`,
            avatar: avatarRichard,
        },
        {
            name: 'Shanai Gough',
            content: `Their software allows us to track, manage and collaborate on our projects
            from anywhere. It keeps the whole team in-sync without being intrusive.`,
            avatar: avatarShanai,
        },
        {
            name: 'Ali Bravo',
            content: `We have been able to cancel so many other subscriptions since using 
            Manage. There is no more cross-channel confusion and everyone is much 
            more focused.`,
            avatar: avatarAli,
        },
    ]
    return (
        <section className="mx-auto w-11/12 max-w-screen-xl pb-20">
            <h2 className="mb-8 text-center">What they&#39;ve said</h2>
            <div className="mb-8">
                <Swiper
                    modules={[Pagination]}
                    slidesPerView={1}
                    direction="horizontal"
                    centeredSlides={true}
                    breakpoints={{
                        '640': {
                            slidesPerView: 2,
                        },
                        '768': {
                            slidesPerView: 3,
                            spaceBetween: 40,
                            centeredSlides: false,
                        },
                    }}
                    spaceBetween={50}
                    pagination={{
                        clickable: true,
                    }}
                >
                    {testimonials.map((testi, i) => {
                        return (
                            <SwiperSlide key={i}>
                                <div className="flex h-full flex-col">
                                    <div className="mx-auto w-20 translate-y-10">
                                        <Image
                                            src={testi.avatar}
                                            alt={`Avart of ${testi.name}`}
                                        />
                                    </div>
                                    <div className="flex-1 bg-very-light-gray p-8 pt-16 text-center">
                                        <h3 className="mb-4">{testi.name}</h3>
                                        <p>{testi.content}</p>
                                    </div>
                                </div>
                            </SwiperSlide>
                        )
                    })}
                </Swiper>
            </div>

            <div className="flex justify-center">
                <Button variant="primary" internalHref="/">
                    Get Started
                </Button>
            </div>
        </section>
    )
}

const SectionSimplify = () => {
    return (
        <section className="bg-red-full">
            <div className="mx-auto w-11/12 py-20 text-center">
                <h2 className="mb-8 text-4xl font-medium text-white">
                    Simplify how your team works today
                </h2>
                <Button variant="accent" internalHref="/">
                    Get Started
                </Button>
            </div>
        </section>
    )
}
